swagger: '2.0'
info:
  title: ForkLine API Gateway
  version: 1.0.0
host: c3afb43921bc.ngrok-free.app
schemes:
  - https
basePath: /
paths:
  /health:
    get:
      summary: Health check
      description: Returns API Gateway status
      responses:
        '200':
          description: API Gateway is running
          schema:
            type: object
            properties:
              status:
                type: string
              message:
                type: string
